"""added allergic and diet type in ingredient

Revision ID: 1c28462c052a
Revises: aaceebfe9545
Create Date: 2025-04-12 21:40:50.748853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c28462c052a'
down_revision: Union[str, None] = 'aaceebfe9545'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('allergic_info', sa.JSON(), nullable=True))
    op.add_column('ingredients', sa.Column('diet_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredients', 'diet_type')
    op.drop_column('ingredients', 'allergic_info')
    # ### end Alembic commands ###
