"""add scan history relationship

Revision ID: fcf5a0dab27d
Revises: 605bfa8313bb
Create Date: 2025-03-21 17:33:44.076205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcf5a0dab27d'
down_revision: Union[str, None] = '605bfa8313bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scan_history_id', table_name='scan_history')
    op.drop_constraint(None, 'scan_history', type_='foreignkey')
    op.create_foreign_key(None, 'scan_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scan_history', type_='foreignkey')
    op.create_foreign_key(None, 'scan_history', 'users', ['user_id'], ['id'])
    op.create_index('ix_scan_history_id', 'scan_history', ['id'], unique=False)
    # ### end Alembic commands ###
