"""add product and update ingredient

Revision ID: xxxx
Revises: fcf5a0dab27d
Create Date: 2025-03-22 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'xxxx'
down_revision: Union[str, None] = 'fcf5a0dab27d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('generic_name', sa.String(), nullable=True),
    sa.Column('brands', sa.String(), nullable=True),
    sa.Column('ingredients', sa.JSON(), nullable=True),
    sa.Column('ingredients_text', sa.String(), nullable=True),
    sa.Column('ingredients_analysis', sa.JSON(), nullable=True),
    sa.Column('nutriscore', sa.JSON(), nullable=True),
    sa.Column('nutrient_levels', sa.JSON(), nullable=True),
    sa.Column('nutriments', sa.JSON(), nullable=True),
    sa.Column('data_quality_warnings', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.add_column('ingredients', sa.Column('description', sa.String(), nullable=True))
    op.add_column('ingredients', sa.Column('origin', sa.String(), nullable=True))
    op.add_column('ingredients', sa.Column('allergens', sa.String(), nullable=True))
    op.add_column('ingredients', sa.Column('vegan', sa.Boolean(), nullable=True))
    op.add_column('ingredients', sa.Column('vegetarian', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_column('ingredients', 'description')
    op.drop_column('ingredients', 'origin')
    op.drop_column('ingredients', 'allergens')
    op.drop_column('ingredients', 'vegan')
    op.drop_column('ingredients', 'vegetarian')
    # ### end Alembic commands ###
